# Generated by Django 4.2.29 on 2026-09-14 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_awardset_competition_awards_given_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="bot_args",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\x20-\\x7e]*$",
                        "Only printable ASCII characters are allowed.",
                    )
                ],
            ),
        ),
    ]
